[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "openai>=1.93.0",
    "pypdf2==3.0.1",
    "python-dotenv>=1.1.1",
    "streamlit>=1.46.1",
]
